export const TYPES = {
	ADD_TO_CART: '@ADDTO_CART',
	REMOVE_CART: '@REMOVE_CART',
	ADD_WISH_LIST: '@ADD_WISH_LIST',
	REMOVE_WISH_LIST: '@REMOVE_WISH_LIST',
	SEE_PRODUCTS_HANDLE: '@SEE_PRODUCTS_HANDLE',
};
